#!/usr/bin/env python3
""" student script used to validate the project
"""
import os
import json
import subprocess
import signal
import sys
import re
import zipfile

from dataclasses import dataclass
from pathlib import Path
from io import BytesIO
from typing import (
    Dict, List, Any, Optional,
    cast, Tuple,
)

# (todo) : not a standard import
import requests

#---
# Internals
#---

##
## config
##

_COLORS_SUCCESS     = '\033[92m'
_COLORS_FAIL        = '\033[91m'
_COLORS_WARN        = '\033[33m'
_COLORS_INFO        = '\033[94m'
_COLORS_END         = '\033[0m'

_URL_GIT_HTTP       = 'https://git.ecole2600.com'
_URL_GIT_SSH        = 'git@git.ecole2600.com'
_SENTINEL_SERVER    = 'https://sentinel.ecole2600.com'
_SENTINEL_VERSION   = '2.0.2'

_BANNER = rf"""
  _________              __  .__              .__
 /   _____/ ____   _____/  |_|__| ____   ____ |  |
 \_____  \_/ __ \ /    \   __\  |/    \_/ __ \|  |
 /        \  ___/|   |  \  | |  |   |  \  ___/|  |__
/_______  /\___  >___|  /__| |__|___|  /\___  >____/
        \/     \/     \/             \/     \/       {_SENTINEL_VERSION}
"""

##
## classes
##

@dataclass
class _UserInfo():
    """ user information """
    email:      str
    url:        str
    commit:     str
    git_dir:    Path

@dataclass
class _APIInfo():
    """ returned API information """
    status: int
    data:   Optional[Dict[str,Any]]
    raw:    bytes

@dataclass
class _ProjectInfo():
    """ project request information """
    name:       str
    type:       str
    requests:   List[Dict[str,Any]]
    raw:        Dict[str,Any]

@dataclass
class _ProjectResult():
    """ project result information """
    files:      List[Tuple[str,BytesIO]]
    requests:   List[Dict[str,Any]]

##
## custom exception
##

class _SentinelException(Exception):
    """ sentinel general exception class """

##
## helpers
##

def _warning(text: str) -> None:
    """ display string in stderr with yellow color
    """
    print(f"{_COLORS_WARN}WARNING: {text}{_COLORS_END}", file=sys.stderr)

def _run_cmd(git_dir: Path, command: Tuple[str,...], error_msg: str) -> str:
    """ run a command using subprocess
    """
    with subprocess.Popen(
        command,
        stdout  = subprocess.PIPE,
        text    = True,
        cwd     = git_dir
    ) as process:
        process.wait()
        stdout, _ = process.communicate()
        if process.returncode != 0:
            raise _SentinelException(error_msg)
    return stdout.strip()

def _api_request(
    action: str,
    route:  str,
    data:   Optional[Dict[Any,Any]] = None,
    form:   Optional[Dict[Any,Any]] = None,
    files:  Optional[List[Tuple[str,BytesIO]]] = None,
) -> _APIInfo:
    """ performs api request using standard urllib3 package
    """
    try:
        if not form:
            form = {}
        form.update({'version': _SENTINEL_VERSION})
        test = getattr(requests, action)(
            url     = f"{_SENTINEL_SERVER}{route}",
            files   = files,
            json    = data,
            data    = form,
            timeout = 60,
        )
        return _APIInfo(
            status  = test.status_code,
            data    = test.json() if test.status_code == 200 else None,
            raw     = test.content
        )
    except requests.exceptions.ConnectionError as err:
        raise _SentinelException(
            '[requests] Unable to interact with the server (max try)'
        ) from err
    except requests.exceptions.ReadTimeout as err:
        raise _SentinelException(
            '[request] API request timeout, abord'
        ) from err

##
## preliminary check
##

def __preliminary_check_tags(userinfo: _UserInfo) -> None:
    """ check if the current commit is associated with sentinel TAGs
    """
    if not (
        stdout := _run_cmd(
            userinfo.git_dir,
            ('git', 'tag', '--contains', f"{userinfo.commit}"),
            '[git] Unable to check commit validity',
        )
    ):
        return
    sentinel_tags = []
    for tag in stdout.split('\n'):
        if not re.match("^(student|admin|final)-[0-9A-Za-z]+$", tag):
            continue
        sentinel_tags.append(tag)
    if not sentinel_tags:
        return
    workaround = '\n   * '.join(sentinel_tags)
    raise _SentinelException(
        f"[git] Commit already tested in TAG:\n   * {workaround}"
    )

def __preliminary_check_commit_valid(userinfo: _UserInfo) -> None:
    """ check if the commit has been pushed
    """
    if not _run_cmd(
        userinfo.git_dir,
        ('git', 'branch', '-r', '--contains', f"{userinfo.commit}"),
        '[git] Unable to check if the commit has been pushed',
    ):
        _warning('current commit not pushed')

def __preliminary_check_url_valid(userinfo: _UserInfo) -> None:
    """ check URL validity
    """
    if userinfo.url.find(_URL_GIT_HTTP) == 0:
        _warning('HTTP repository URL detected, use SSH for posterity')
        return
    if userinfo.url.find(_URL_GIT_SSH) == 0:
        return
    raise _SentinelException('[git] Not valid repository URL')

def _preliminary_check(userinfo: _UserInfo) -> None:
    """ common preliminary checks
    """
    __preliminary_check_commit_valid(userinfo)
    __preliminary_check_url_valid(userinfo)

def _preliminary_check_project(
    project: _ProjectInfo,
    userinfo: _UserInfo,
) -> None:
    """ project-specific preliminary checks
    """
    if project.type == 'asr':
        return
    __preliminary_check_tags(userinfo)

##
## git abstraction
##

def _git_push_tag(git_dir: Path, tag: str) -> None:
    """ manually push tag
    """
    commands = (
        ('git', 'tag', tag),
        ('git', 'push'),
        ('git', 'push', '--tags'),
    )
    for command in commands:
        result = subprocess.run(command, cwd=git_dir, check=False)
        if result.returncode != 0:
            workaround = ' '.join(command)
            raise _SentinelException(
                f"[shell] command '{workaround}' failed o(x_x)o\n"
                'You can manually retry to push the TAG and commits by '
                'using:\n'
                f" 1. git tag '{tag}'\n"
                ' 2. git push\n'
                ' 3. git push --tags'
            )

def _git_check_meta(git_dir: Path) -> _UserInfo:
    """ Fetch user information using git
    """
    # check if the student have uncommited files
    if _run_cmd(
        git_dir,
        ('git', 'status', '-s'),
        '[git] Unable to check git status',
    ):
        raise _SentinelException(
            '[git] Uncommitted files detected, commit your changes '
            'or stash and retry'
        )

    # fetch user information
    commands = {
        'url':      ('git', 'config', '--get', 'remote.origin.url'),
        'email':    ('git', 'config', '--get', 'user.email'),
        'commit':   ('git', 'log', '--format="%H"', '-n', '1'),
    }
    info = {}
    for command in commands.items():
        info[command[0]] = _run_cmd(
            git_dir,
            command[1],
            f"[git] Unable to find '{command[0]}' information",
        ).strip()
    info['commit'] = info['commit'].replace('"', '')

    # generate user information
    return _UserInfo(
        email   = info['email'],
        url     = info['url'],
        commit  = info['commit'],
        git_dir = git_dir,
    )

##
## project params request operations
##

def _request_cmd(
    request:  Dict[str,str],
    userinfo: _UserInfo,
) -> Dict[str,str]:
    """ execute request commands
    """
    proc = subprocess.run(
        request['cmd'],
        stdout      = subprocess.PIPE,
        stderr      = subprocess.PIPE,
        shell       = True,
        encoding    = "utf-8" if os.name != 'nt' else 'latin1',
        check       = False,
        cwd         = userinfo.git_dir,
    )
    return {
        'stdout': proc.stdout,
        'stderr': proc.stderr,
        'returncode': str(proc.returncode),
    }

def _request_file(request: Dict[str,str], userinfo: _UserInfo) -> BytesIO:
    """ handle FileResourceParams request type
    """
    if not (filepath := Path(request['path'])).is_absolute():
        filepath = (userinfo.git_dir/request['path']).resolve()
    # (todo) : better behaviour if file missing
    if not filepath.exists():
        raise _SentinelException(
            f"[file] Unable to find the file '{filepath}'"
        )
    with open(filepath, 'rb') as fileinfo:
        return BytesIO(fileinfo.read())

def _request_dir(request: Dict[str,str], userinfo: _UserInfo) -> BytesIO:
    """ handle DirResourceParams request type
    """
    excludes_re = [re.compile(e) for e in request['exclude']]
    if not (pathname := Path(request['path'])).is_absolute():
        pathname = (userinfo.git_dir/request['path']).resolve()
    if not pathname.exists():
        raise _SentinelException(
            f"[dir] Unable to find the directory prefix '{request['path']}'"
        )
    files = []
    for filepath in pathname.rglob('*'):
        need_exclude = False
        for exclude in excludes_re:
            if exclude.search(str(filepath)):
                need_exclude = True
                break
        if need_exclude:
            continue
        files.append(filepath)
    zip_data = BytesIO()
    with zipfile.ZipFile(zip_data, "w") as zip_file:
        for file in files:
            try:
                zip_file.write(file)
            except (PermissionError, FileNotFoundError):
                pass
    zip_data.seek(0)
    return zip_data

##
## project abstraction
##

def _project_fetch(userinfo: _UserInfo) -> _ProjectInfo:
    """ fetch project information if the project exists
    """
    received = _api_request(
        action  = 'get',
        route   = '/projects/',
        form    = {
            'repoUrl':      userinfo.url,
            'repoCommit':   userinfo.commit,
            'userEmail':    userinfo.email,
        },
    )
    if received.status != 200:
        raise _SentinelException(
            f"[project] {received.raw.decode('utf-8')}"
        )
    data = cast(Dict[str,Any],received.data)
    return _ProjectInfo(
        name        = data['name'],
        type        = data['type'],
        requests    = data['required_cmds'],
        raw         = data,
    )

def _project_exec(
    project:  _ProjectInfo,
    userinfo: _UserInfo,
) -> _ProjectResult:
    """ exec project requests
    """
    mapper = {
        'CmdResourceParams'  : _request_cmd,
        'FileResourceParams' : _request_file,
        'DirResourceParams'  : _request_dir,
    }
    results = _ProjectResult(
        files       = [],
        requests    = [],
    )
    for cmd in project.requests:
        if cmd['type'] not in mapper:
            raise _SentinelException(
                '[project] Error command type. Please contact an assistant'
            )
        data: Any = mapper[cmd['type']](cmd['request'], userinfo)
        if cmd['type'] != 'CmdResourceParams':
            results.files.append(('files', data))
            data = len(results.files) - 1
        results.requests.append({
            'name' : cmd['name'],
            'type' : cmd['type'],
            'data' : data
        })
    return results

def _project_send_result(
    userinfo: _UserInfo,
    results:  _ProjectResult,
) -> Dict[str,Any]:
    """ send requests' results and handle response
    """
    resp = _api_request(
        action  = 'post',
        route   = '/projects/submit',
        files   = results.files,
        form    = {
            'repoUrl':      userinfo.url,
            'repoCommit':   userinfo.commit,
            'userEmail':    userinfo.email,
            'cmds':         json.dumps(results.requests),
        },
    )
    if resp.status != 200:
        raise _SentinelException(f"[project] {resp.raw.decode('utf-8')}")
    return cast(Dict[str,Any],resp.data)

def _project_asr_report(report: Dict[str,Any], userinfo: _UserInfo) -> None:
    """ display the report, generate the tokens file and commit
    """
    # display report
    print("** TESTS **\n")
    success_test_counter = 0
    final_log = []
    max_len = 0
    stoken = report['token_sentinel']
    report = report['tests']
    for test_name, result in report.items():
        if result['success']:
            success_test_counter += 1
            print(f"[{_COLORS_SUCCESS}OK{_COLORS_END}] {test_name}")
            max_len = max(max_len, len(test_name))
        else:
            print(f"[{_COLORS_FAIL}KO{_COLORS_END}] {test_name}")
        if result['log'] != "":
            final_log.append(f"- {test_name} : {result['log']}")
    print(f"\nTotal: {success_test_counter}/{len(report)}\n")
    print("** TOKENS **\n")
    print(
        "\n".join([
            f"- {test_name: <{max_len}} {result['token']}"
            for test_name, result in report.items() if result['success']
        ])
    )
    if len(final_log) > 0:
        print("\n** ERROR LOGS **\n")
        print("\n".join(final_log))

    # generate the tokens file
    tokenfile_path = userinfo.git_dir/'tokens'
    with open(tokenfile_path, 'w', encoding='utf8') as tokens:
        for result in report.values():
            if not result['success']:
                continue
            tokens.write(f"{result['token']}\n")

    # add the tokens file if needed
    if not _run_cmd(
        userinfo.git_dir,
        ('git', 'status', '-s', f"{tokenfile_path}"),
        '[git] Unable to check if the tokens file has changed',
    ):
        _warning(
            'The tokens file has not changed since the last sentinel '
            'request.\nNo TAG will be pushed, but you can manually request '
            'a sentinel if needed:\n'
            f" 1. git tag '{stoken}'\n"
            ' 2. git push`\n'
            ' 3. git push --tags'
        )
        sys.exit(0)
    cmds = (
        ('git', 'add', f"{tokenfile_path}"),
        ('git', 'commit', '-m', 'update tokens file'),
    )
    git_dir = userinfo.git_dir
    try:
        _run_cmd(git_dir, cmds[0], '[git] unable to add tokens file')
        _run_cmd(git_dir, cmds[1], '[git] unable to commit tokens file')
    except _SentinelException as err:
        raise _SentinelException(
            f"{err}\n"
            'You can manually request a sentinel if needed:\n'
            f" 1. git add '{tokenfile_path}'\n"
            ' 2. git commit -m \'update tokens file\'\n'
            f" 3. git tag '{stoken}'\n"
            ' 4. git push\n'
            ' 5. git push --tags'
        ) from err

##
## user abstraction
##

def _userinfo_fetch() -> _UserInfo:
    """ fetch user information using git
    """
    current = Path.cwd()
    home = Path.home()
    while current != home:
        if not (git_dir := current/".git").exists():
            current = current.parent
            continue
        if not git_dir.is_dir():
            current = current.parent
            continue
        if current != Path.cwd():
            print(f"- found project directory at '{str(current)}'")
        return _git_check_meta(git_dir.parent)
    raise _SentinelException("[git] No .git directory found, abord")

##
## main entry
##

def _main() -> None:
    """ The main entry of the project
    """
    try:
        print('[+] prepare sentinel context...')
        prev_handler = signal.signal(signal.SIGINT, signal.SIG_IGN)
        print('[+] find project information...')
        userinfo = _userinfo_fetch()
        print('[+] preliminary checks...')
        _preliminary_check(userinfo)
        print('[+] request project information...')
        project = _project_fetch(userinfo)
        print('[+] project-specific preliminary checks...')
        _preliminary_check_project(project, userinfo)
        print('[+] perform project operations...')
        result = _project_exec(project, userinfo)
        print('[+] send results...')
        report = _project_send_result(userinfo, result)
        if project.type == 'asr':
            print('[+] display report...')
            _project_asr_report(report, userinfo)
        print('[+] requesting sentinel...')
        _git_push_tag(userinfo.git_dir, report['token_sentinel'])
        print('[+] restore original context...')
        signal.signal(signal.SIGINT, prev_handler)
        sys.exit(0)
    except _SentinelException as err:
        print(f"{_COLORS_FAIL}{err}{_COLORS_END}", file=sys.stderr)
        sys.exit(1)

#---
# Public
#---

if __name__ == "__main__":
    print(_BANNER)
    _main()
